# Generated by Django 2.2.3 on 2020-09-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
