# Generated by Django 2.2.3 on 2020-09-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200915_1834'),
    ]

    operations = [
    ]
